# Generated by Django 5.2.4 on 2025-07-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={"verbose_name": "seguidor", "verbose_name_plural": "seguidores"},
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together=set(),
        ),
    ]
